### ISSUE TITLE
Can't continue run in background when restart device automatically.

### ISSUE THREAD

**Issue by bruintangible** [yarodevuci/backgroundTask#1]
I try your method, but I found the method can't achieve to reboot to device, the application can't run automatically in background. Have any method auto start run the method when the device reboot? I try to the code and change the call timer method and startBackgroundTask  in appdelegate file. I test in the iOS10 beta8 ipad device(XCode 8 beta6). thank you very much.

**Comment by yarodevuci** [comment]
I will implement such feature later

**Comment by bruintangible** [comment]
I  expect you implement the function. Thank you~

**Comment by yarodevuci** [comment]
as a temporary solution, I recommend using Cydia tweak Watchdog, if your iDevice is Jaibroken..

**Comment by bruintangible** [comment]
I encounter problem is that can continue run in background when I reboot device before the iOS9 at the non Jailbroken device. But after iOS10 , when I reboot , it will interrupt app. I was not found solution after iOS10. ><

**Comment by yarodevuci** [comment]
Hm, so it does not work on iOS 10 ? 
Haven't tested on iOS10
I am using it on iOS 8
Will look into it later on
So for right now , I can't offer any support for iOS 10

**Comment by zhouhao27** [comment]
Any solution found after device reboot?

**Comment by yarodevuci** [comment]
@zhouhao27 no

**Comment by zhouhao27** [comment]
@yarodevuci Do you know if any event the application can receive after device reboot so that we can restart the background task?

**Comment by yarodevuci** [comment]
@zhouhao27 I really have no idea, I don't it's even possible with latest iOS version.

**Comment by bruintangible** [comment]
@yarodevuci I am not found any method in last ios Version too.

**Comment by yarodevuci** [comment]
@bruintangible yea it's impossible
