### ISSUE TITLE
Apple Reject...

### ISSUE THREAD

**Issue by Spacelapp** [yarodevuci/backgroundTask#2]
:(

Performance - 2.5.4

Your app declares support for audio in the UIBackgroundModes key in your Info.plist but did not include features that require persistent audio.

Next Steps

The audio key is intended for use by apps that provide audible content to the user while in the background, such as music player or streaming audio apps. Please revise your app to provide audible content to the user while the app is in the background or remove the "audio" setting from the UIBackgroundModes key.

**Comment by yarodevuci** [comment]
This is of course an apple reject! This method only for personal use
