### ISSUE TITLE
App stops afterwhile ? 

### ISSUE THREAD

**Issue by fadylateef** [yarodevuci/backgroundTask#3]
I am using your test project in background , after about 15:30 minutes the app stops and when open the app  is opens like it is the first time . 

I'm using it by running directly from xcode into my iphone 7 .

Thanks in  advance

**Comment by yarodevuci** [comment]
@fadylateef are you running it on latest Xcode and ios 10.3?

**Comment by fadylateef** [comment]
Yes , it utilizes large energy and memory ... What latest iOS version that does not suspend apps ? 

I tried it on iOS 9.3 but xcode refuses as it does not support old models.

**Comment by yarodevuci** [comment]
Oh wow, I didn't even know. I used on ios 8.4. Maybe downgrading xCode is an option?
