### ISSUE TITLE
Will apple reject my app if i have already registered and use required items.

### ISSUE THREAD

**Issue by PmAbi1993** [yarodevuci/backgroundTask#4]
I am developing a peer to peer VOIP application. So I have already implemented the necessary functions for VOIP and audio. But the app is being closed after ten minutes.

I was wondering whether I could use this background technique since I have already implemented the VOIP functionality. Will apple know that I have used this technique as I believe they don't look at our source code. I don't want to rely on pushkit extensively as I don't have a server for connection process. Just curious.

**Comment by yarodevuci** [comment]
I doubt they will reject it. Let me know how it goes.
