### ISSUE TITLE
BackgroundTask.stopBackgroundTask() error

### ISSUE THREAD

**Issue by ttakumat** [yarodevuci/backgroundTask#9]
I’ve been trying to use this on ios11 Swift 5. But when BackgroundTask.stopBackgroundTask() is called, it crushes and gives out error on player.stop().
Need some help...
Also thanks for the amazing work!

**Comment by yarodevuci** [comment]
Hi
I will check what's up

**Comment by ttakumat** [comment]
Wow thanks for super quick response!
Looking forward for a solution!
Thanks!

**Comment by yarodevuci** [comment]
@ttakumat are you testing it on device or simulator ?

**Comment by ttakumat** [comment]
Device and simulator and both crushes...

**Comment by yarodevuci** [comment]
@ttakumat Try pull latest version. Should be good.

**Comment by yarodevuci** [comment]
@ttakumat If you still having an error post a crash log from console here..

**Comment by 0xtoko** [comment]
It’s EXC_BAD_ACCESS so it doesn’t output crash log.
Is there a way to debug this?

**Comment by yarodevuci** [comment]
What exact iOS version simulator is? I tested on 11.0.1 no issues

**Comment by 0xtoko** [comment]
Sorry for late reply.
I'm running ios 11.3.1.
I've also found out that background tasking itself wasn't working in the first place.
Am I doing something wrong?
I've added "App plays audio or streams audio/video using AirPlay" in "Required background modes" inside info.plist. Then
backgroundTask.startbackgroundTask() in func applicationDidEnterBackground
backgroundTask.stopbackgroundTask() in func applicationWillEnterForeground
both in Appdelegate.swift.
I have count up timer running in viewcontroller but counting stops when app is closed...
when opening the app it gives "Thread 1: EXC_BAD_ACCESS (code=1, address=0x48)" on player.stop() in BackgroundTask.swift file.

here is a screenshot
![Screen Shot 2019-05-15 at 22 53 27](https://user-images.githubusercontent.com/50645218/57781072-67000400-7764-11e9-9aeb-e78647fc773b.jpg)

**Comment by yarodevuci** [comment]
@ttakumat by app close you mean removed from multitask or just like when home button pressed?
Can you also test the issue on iOS 12?

**Comment by 0xtoko** [comment]
It’s home button press. 
I’ll borrow my friends phone to test today.

**Comment by 0xtoko** [comment]
borrowed ios12.2 iPhone but it did the same thing...

**Comment by yarodevuci** [comment]
@ttakumat Tested on Simulator 12.2, pressed home button, I can see the log. Opened the app, pressed stop and no crashes for me at all.. Tested on Simulator XR 12.2

**Comment by yarodevuci** [comment]
@ttakumat 
I noticed that u testing in your project. What If you run my project. Same thing?

**Comment by 0xtoko** [comment]
Tried and same thing. 
Crushes when reopened...with bad access
Does it not happen to you?

**Comment by 0xtoko** [comment]
I think I've found a solution!
Just replacing code inside playaudio() function with this got background task working for me.
Its just a copy paste from stackoverflow though.

"""


        guard let url = Bundle.main.url(forResource: "blank", withExtension: "wav") else { return }
        
        do {
            try AVAudioSession.sharedInstance().setCategory(.playback, mode: .default)
            try AVAudioSession.sharedInstance().setActive(true)
            
            player = try AVAudioPlayer(contentsOf: url, fileTypeHint: AVFileType.wav.rawValue)
            
            guard let player = player else { return }
            
            player.numberOfLoops = -1
            player.volume = 0.01
            player.play()
            
        } catch let error {
            print(error.localizedDescription)
        }
    }

"""

**Comment by 0xtoko** [comment]
and I've also changed
```
var player = AVAudioPlayer() 
```
to
```
var player: AVAudioPlayer?
```

**Comment by yarodevuci** [comment]
@ttakumat You used my latest commit right for Swift 5 update?

**Comment by 0xtoko** [comment]
Oh, for that I was accidentally using old commit for my project, but I was using the swift 5 updated version to run your project. I’ve noticed this when I tested it with my friends phone.
Unfortunately updated swift 5 version didn’t work for me either. 
 The one I replaced inside playaudio() is working perfectly fine on both project!

**Comment by yarodevuci** [comment]
Ok sounds good. I ll close the issue

**Comment by 0xtoko** [comment]
Thanks for the help!
Your project is amazing!
